### ISSUE TITLE
Small Solar Panel Setup to Charge Phones/Batteries/Etc

### ISSUE THREAD

**Issue by adobito** [SoPR/maria-tech-brigade-effort#15]
Completed and moved to Wiki.

**Comment by adobito** [comment]
~~BTW if anyone can help make a diagram for this that would be great.~~

**Comment by chamakits** [comment]
I can try tomorrow night when I get home.
I do not promise amazing results, but I'll try, jajaja.

By all means, if anybody is graphic designer, go for it, you'll have better results than me.

**Comment by agostof** [comment]
No soy graphic designer pero yo tenia una idea bien simple del diagrama usando [glyphicons](http://glyphicons.com/) para los componentes principales. 
>celdas: glyphicons-show-thumbnails; 16 - g; `&#xe157;`
bateria: glyphicons-battery-charging; 77 -e; `&#xe765;`
inverter: glyphicons-charging-station; 48 - a; `&#xe471;`
controller_opcion1: glyphicons-tree-structure; 70 - b; `&#xe692;`
controller_opcion2: glyphicons-macbook; 17 - b; `&#xe162;`

El del controller creo que habria que dibujarlo de todos modos, pero como dije es una idea bien básica.
No se si algo asi ayudaria.

**Comment by astrogexo** [comment]
Conozco unos graphic designers. I'm getting in touch with them. Also, should we suggest ready-made USB solar solutions?

**Comment by agostof** [comment]
IMHO, suggesting ready-made solar powered chargers makes sense. There are other USB-powered products used for camping and other outdoor activities that might work, but many tend to be pricey.

**Comment by adobito** [comment]
I explicitly stayed away from ready made solutions because they tend to be expensive, they tend to offer very little power and they make solar energy be this mystical hard to grasp thing. This setup can be extended and has the potential to power different things (5v USB, 12v Car Peripherals, 110V AC low power devices).

@agostof I'm going to draw a small diagram on paper and upload it which explains how everything is plugged in. The diagram is very simple and the idea is to have something clean and easy to understand but I have no patience for graphic work.

**Comment by adobito** [comment]
Drew a simple diagram on a notebook: https://drive.google.com/open?id=0Bwy3lh8U5KLzTF9EUnE5dkY0R0k

**Comment by ecrespomit** [comment]
Algo asi? Lo hice en minutos con draw.io btw
* Asumo q el arrow de la bateria de carro debe ir en ambas direcciones (aunque todas tecnicamente son ambas direcciones)
![solar_power_maria_pr](https://user-images.githubusercontent.com/7256527/30880290-12f495a2-a2d0-11e7-88b8-bd29d47e5d50.png)

**Comment by adobito** [comment]
@ecrespomit hay alguna manera que me des edit access a eso? Donde dice `Charge Converter` deberia decir `Charge Controller` y quiero arreglarlo.

BTW looks good! Gracias! 👍

**Comment by ecrespomit** [comment]
No encuentro bien como share for edit (only export). Let me look into it.
Si quieres tratarlo from scratch, puedes entrar a draw.io, free y no hay q sign in, etc.

Aquí con el change: 
![solar_power_maria_pr 1](https://user-images.githubusercontent.com/7256527/30883854-8989a1ac-a2db-11e7-9083-9f4e73f0a3dc.png)

**Comment by adobito** [comment]
Looks solid! voy a edit y a~adirlo. Thanks!

EDIT: Added to top level post.

**Comment by oldmud0** [comment]
With an inverter, you are converting DC power to AC power... and then back to DC power. This is extremely inefficient, and as an alternative, one should wire multiple car lighter ports in parallel with USB chargers connected to each lighter, unless there is a serious necessity for AC power. (Or you can try splicing the cables, but this is an irreversible process.)

**Comment by adobito** [comment]
The reason I recommend the inverter is because it's more flexible. It already comes with 4 USB ports and people are more likely to have AC multiplugs and AC chargers at their house. You could keep adding DC 12v ports but the added cost for the small gain in inefficiency and loss of flexiblity is a big no-no to me.

**Comment by ecrespomit** [comment]
Have you guys considered something like this? (Bonus if we get that Anker discount!)
https://smile.amazon.com/Anker-Charger-PowerPort-iPhone-Galaxy/dp/B012YUJJM8/ref=sr_1_3?ie=UTF8&qid=1506464042&sr=8-3&keywords=anker+solar
Decent enough for the price and portability, can also easily be used along a power bank to store juice for night hours.

**Comment by adobito** [comment]
@ecrespomit Yes I've looked into this before and I actually own a non-anker solar panel of that type. It's a decent solution for charging USB devices but requires more work to get good solar coverage since you can't just put that on the roof and charge your power bank downstairs. Any shade (even if it's just because the sun is coming through a fence) lowers the output significantly on all solar panels and the uninterrupted sunlight is key.

That being said, it's waaaaay easier to setup than this since it's just plug and play.

**Comment by agostof** [comment]
@jluzonpr If we are expecting this to be assembled by unexperienced users, I suggest we add some basic safety instructions for assembly and operation.

**Comment by adobito** [comment]
@agostof added a basic warning. if you have any more specific suggestions please let me know

**Comment by adobito** [comment]
https://github.com/SoPR/maria-tech-brigade-effort/wiki/50w-Solar-Panel-Setup-to-Charge-Phones-Batteries

Closing.
