### ISSUE TITLE
List of donation centers inside and outside the island 

### ISSUE THREAD

**Issue by vLUCYANv** [SoPR/maria-tech-brigade-effort#2]
We should have a centralized list of all donation centers inside and outside the island. With details of directions, hours, dates and possible shipping dates to the island and where they are taking the items. We also need a list of items each location will be accepting

**Comment by jpadilla** [comment]
@mfjv88 has been working on this http://www.diasporicans.com

**Comment by froi** [comment]
This is the project: https://github.com/mfjv88/diasporicans

Let's focus on this. @mfjv88 has asked me for help with it.

**Comment by vacas** [comment]
@Specialist17 is helping me here too.

**Comment by froi** [comment]
We should move discussion of this to #3
