### ISSUE TITLE
Maria Tech Brigade comms team

### ISSUE THREAD

**Issue by froi** [SoPR/maria-tech-brigade-effort#25]
As our group has grown our community and projects are getting noticed outside of our brigade. We have been approached by various media and NGO organizations asking for interviews, write-ups, and general questions on who we are and how they can collaborate. 

This has created a need to put in place a more strategic comms plan. As part of this effort, I will be establishing our comms team. This team will be in charge of our official comms and message. They will also filter inquiries about projects to the project authors and generally work to connect the right people and ensure that credit is given where it is due. This team will be made up of a small group of volunteers that will work with the community and the founding members to keep us on message.

That does not mean that we are going to do things without the community's input. The comms team will be using Github issues to gather the ideas of the community. This will help mold the way we interact with traditional and social media.

Please give us your thoughts on what you would like to see from your comms team going forward.

Thanks!

**Comment by miguelrios** [comment]
María en slack:

> Qué quieren en términos de comunicaciones? En artículos que he leído sobre el María Tech Brigade veo el mensaje bien definido. Si lo que quieren es un media tour o enviar comunicados de prensa para anunciar proyectos nuevos, eso se puede hacer. Al final nadie conoce mejor el trabajo que el que lo está haciendo. Comunicaciones solo pone el mensaje lindo.

> Entre los que estén trabajando escojan un portavoz o 2 por área y cuando lleguen los requests de entrevistas lo pasan al portavoz. Si esa persona quiere un coaching de entrevista, que avise. Pero lo más que pienso que habría que trabajar es explicar las cosas de una manera simple.

**Comment by mj16** [comment]
Llenen los blancos:

Información general sobre MTB que todos deben saber: ¿Qué es el MTB? ¿Qué hace? ¿Cómo se formó? ¿Quiénes lo componen? Descripción general de los proyectos que están trabajando.

Proyectos específicos: Escoger portavoz.

Para practicar explicar el proyecto, busca un niño de 12 años o menos. 1) Captura su atención 2) Explícale lo que estás haciendo.
