### ISSUE TITLE
Map properties with FEMA status

### ISSUE THREAD

**Issue by froi** [SoPR/maria-tech-brigade-effort#7]
Find a way to map house by house what was destroyed and if FEMA claims have been filed as govt service.

[Cate Long tweet with the idea](https://twitter.com/cate_long/status/911345780925059072)

Detroit did something similar [here](http://datadrivendetroit.org/wp-content/uploads/2010/04/DetroitDataCollaborativeRelease.pdf)

**Comment by mango314** [comment]
Properties are available off the Catastro and data.pr.gov still seems to be online.  How do we get FEMA claims?

**Comment by mango314** [comment]
@froi FEMA's own coverage is spotty like a radio with bad reception.  Here's the page
https://www.fema.gov/hurricane-maria and here are the tweets discussing which certain information was missing.

https://www.washingtonpost.com/news/politics/wp/2017/10/06/fema-buried-updates-on-puerto-rico-here-they-are/

http://status.pr

And the official PR web site.  Slowly piecing it together.

**Comment by karmacelina** [comment]
what if we use geotagged photos and something like http://arcg.is/2yKUlEr ? ESRI is already helping with some efforts. Contact person in Slack channel is Carlos Saavedra

**Comment by froi** [comment]
Closing up. Thank you all for you support and dedication 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
